/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Pro 65 Md34.c                         *
* Font:        HelveticaNeueLT Pro 65 Md                             *
* Height:      34                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 34                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  0030 - 0039                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTPro65Md34;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0030[ 68] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,__XXXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXXX__,__XXXX__,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXX____,
  ______XX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0031[ 68] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,XX______,
  _______X,XX______,
  _______X,XX______,
  _____XXX,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0032[ 68] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,XXX_____,
  _____XXX,XXXXX___,
  ____XXXX,XXXXXX__,
  ___XXXX_,___XXX__,
  ___XXX__,____XXX_,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  ________,___XXXX_,
  ________,___XXX__,
  ________,__XXXX__,
  ________,XXXXX___,
  _______X,XXX_____,
  ______XX,XX______,
  ____XXXX,X_______,
  ____XXXX,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0033[ 68] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,__XXX___,
  __XXX___,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  ________,___XXX__,
  ________,__XXX___,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXXXX__,
  ________,___XXX__,
  ________,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXXX___,___XXXX_,
  __XXXX__,__XXXX__,
  __XXXXXX,XXXXXX__,
  ____XXXX,XXXXX___,
  ______XX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0034[ 68] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,_XXX____,
  ________,XXXX____,
  _______X,XXXX____,
  _______X,XXXX____,
  ______XX,XXXX____,
  _____XXX,_XXX____,
  _____XX_,_XXX____,
  ____XXX_,_XXX____,
  ___XXX__,_XXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  _XXX____,_XXX____,
  XXX_____,_XXX____,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0035[ 68] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  ___XXX__,________,
  ___XX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX__X,XX______,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXXX__,
  __XXXX__,__XXXX__,
  _XXXX___,___XXXX_,
  ________,____XXX_,
  ________,____XXX_,
  ________,____XXX_,
  _XXX____,____XXX_,
  _XXX____,___XXXX_,
  __XXX___,__XXXX__,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  _____XXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0036[ 68] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XXX_____,
  _____XXX,XXXXX___,
  ____XXXX,XXXXXX__,
  ___XXX__,__XXXX__,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  __XX____,________,
  _XXX___X,XX______,
  _XXX_XXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  _XXXXX__,__XXXX__,
  _XXXX___,___XXXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  __XX____,____XXX_,
  __XXX___,___XXXX_,
  __XXXX__,__XXXX__,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXX____,
  ______XX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0037[ 68] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  ________,___XXX__,
  ________,__XXX___,
  ________,_XXX____,
  ________,_XXX____,
  ________,XXX_____,
  _______X,XXX_____,
  _______X,XX______,
  _______X,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0038[ 68] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,__XXXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  ___XXX__,__XXX___,
  ____XXXX,XXXX____,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXX___,___XXX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  __XXX___,___XXX__,
  __XXXXXX,XXXXXX__,
  ___XXXXX,XXXX____,
  ______XX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md34_0039[ 68] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,__XXXX__,
  _XXXX___,___XXX__,
  _XXX____,____XX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXXX___,___XXXX_,
  __XXXX__,__XXXXX_,
  __XXXXXX,XXXXXXX_,
  ___XXXXX,XXX_XXX_,
  _____XXX,X___XXX_,
  ________,____XX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  ___XXX__,__XXX___,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXX____,
  ______XX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHelveticaNeueLTPro65Md34_CharInfo[10] = {
   {  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0030 } /* code 0030 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0031 } /* code 0031 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0032 } /* code 0032 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0033 } /* code 0033 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0034 } /* code 0034 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0035 } /* code 0035 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0036 } /* code 0036 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0037 } /* code 0037 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0038 } /* code 0038 */
  ,{  16,  16,  2, acGUI_FontHelveticaNeueLTPro65Md34_0039 } /* code 0039 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md34_Prop1 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md34_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTPro65Md34 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,34 /* height of font  */
  ,34 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTPro65Md34_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,21 /* Height of capital characters */
};

