/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HoloLens MDL2 Assets27.c                              *
* Font:        HoloLens MDL2 Assets                                  *
* Height:      27                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 27                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  EBA0 - EBB5                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHoloLensMDL2Assets27;

/* Start of unicode area <Private Use Area> */
GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA0[162] = { /* code EBA0 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXXXX,________,
  ___XXX__,________,________,________,___XXXXX,________,
  ___XXX__,________,________,________,___XXXXX,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA1[162] = { /* code EBA1 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXXXX,________,
  ___XXX_X,XXX_____,________,________,___XXXXX,________,
  ___XXX_X,XXX_____,________,________,___XXXXX,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA2[162] = { /* code EBA2 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXXXX,________,
  ___XXX_X,XXXXX___,________,________,___XXXXX,________,
  ___XXX_X,XXXXX___,________,________,___XXXXX,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA3[162] = { /* code EBA3 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,________,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,________,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA4[162] = { /* code EBA4 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA5[162] = { /* code EBA5 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA6[162] = { /* code EBA6 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA7[162] = { /* code EBA7 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA8[162] = { /* code EBA8 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBA9[162] = { /* code EBA9 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBAA[162] = { /* code EBAA */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBAB[162] = { /* code EBAB */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX___XX,X_______,________,________,___XXX__,________,
  _XXX_XXX,X_______,________,________,___XXX__,________,
  _XXXXXXX,________,________,________,___XXXXX,________,
  ___XXX__,________,________,________,___XXXXX,________,
  ___XXX__,________,________,________,___XXXXX,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBAC[162] = { /* code EBAC */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX___XX,X_______,________,________,___XXX__,________,
  _XXX_XXX,XXX_____,________,________,___XXX__,________,
  _XXXXXXX,_XX_____,________,________,___XXXXX,________,
  ___XXX__,_XX_____,________,________,___XXXXX,________,
  ___XXX__,XXX_____,________,________,___XXXXX,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX_X,XXX_____,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBAD[162] = { /* code EBAD */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXX___,________,________,___XXX__,________,
  XXX____X,X_XXX___,________,________,___XXX__,________,
  XXX___XX,X_XXX___,________,________,___XXX__,________,
  _XXX_XXX,X_XXX___,________,________,___XXX__,________,
  _XXXXXXX,__XXX___,________,________,___XXXXX,________,
  ___XXX__,_XXXX___,________,________,___XXXXX,________,
  ___XXX__,XXXXX___,________,________,___XXXXX,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX_X,XXXXX___,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBAE[162] = { /* code EBAE */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,________,________,___XXX__,________,
  XXX___XX,X_XXXXXX,________,________,___XXX__,________,
  _XXX_XXX,X_XXXXXX,________,________,___XXX__,________,
  _XXXXXXX,__XXXXXX,________,________,___XXXXX,________,
  ___XXX__,_XXXXXXX,________,________,___XXXXX,________,
  ___XXX__,XXXXXXXX,________,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,________,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBAF[162] = { /* code EBAF */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XX______,________,___XXX__,________,
  XXX____X,X_XXXXXX,XX______,________,___XXX__,________,
  XXX___XX,X_XXXXXX,XX______,________,___XXX__,________,
  _XXX_XXX,X_XXXXXX,XX______,________,___XXX__,________,
  _XXXXXXX,__XXXXXX,XX______,________,___XXXXX,________,
  ___XXX__,_XXXXXXX,XX______,________,___XXXXX,________,
  ___XXX__,XXXXXXXX,XX______,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XX______,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBB0[162] = { /* code EBB0 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXX___,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXX___,________,___XXX__,________,
  XXX___XX,X_XXXXXX,XXXXX___,________,___XXX__,________,
  _XXX_XXX,X_XXXXXX,XXXXX___,________,___XXX__,________,
  _XXXXXXX,__XXXXXX,XXXXX___,________,___XXXXX,________,
  ___XXX__,_XXXXXXX,XXXXX___,________,___XXXXX,________,
  ___XXX__,XXXXXXXX,XXXXX___,________,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXX___,________,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBB1[162] = { /* code EBB1 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,X_______,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,X_______,___XXX__,________,
  XXX___XX,X_XXXXXX,XXXXXXXX,X_______,___XXX__,________,
  _XXX_XXX,X_XXXXXX,XXXXXXXX,X_______,___XXX__,________,
  _XXXXXXX,__XXXXXX,XXXXXXXX,X_______,___XXXXX,________,
  ___XXX__,_XXXXXXX,XXXXXXXX,X_______,___XXXXX,________,
  ___XXX__,XXXXXXXX,XXXXXXXX,X_______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,X_______,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBB2[162] = { /* code EBB2 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XX______,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XX______,___XXX__,________,
  XXX___XX,X_XXXXXX,XXXXXXXX,XX______,___XXX__,________,
  _XXX_XXX,X_XXXXXX,XXXXXXXX,XX______,___XXX__,________,
  _XXXXXXX,__XXXXXX,XXXXXXXX,XX______,___XXXXX,________,
  ___XXX__,_XXXXXXX,XXXXXXXX,XX______,___XXXXX,________,
  ___XXX__,XXXXXXXX,XXXXXXXX,XX______,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XX______,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBB3[162] = { /* code EBB3 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  XXX___XX,X_XXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  _XXX_XXX,X_XXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  _XXXXXXX,__XXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,________,
  ___XXX__,_XXXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,________,
  ___XXX__,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,___XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBB4[162] = { /* code EBB4 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  XXX___XX,X_XXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  _XXX_XXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  _XXXXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,________,
  ___XXX__,_XXXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,________,
  ___XXX__,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,X__XXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHoloLensMDL2Assets27_EBB5[162] = { /* code EBB5 */
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  __XX_XXX,________,________,________,________,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_______,________,________,___XXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX____X,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXX___XX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXX_XXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX__,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX__,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX__,________,________,________,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHoloLensMDL2Assets27_CharInfo[22] = {
   {  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA0 } /* code EBA0 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA1 } /* code EBA1 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA2 } /* code EBA2 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA3 } /* code EBA3 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA4 } /* code EBA4 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA5 } /* code EBA5 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA6 } /* code EBA6 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA7 } /* code EBA7 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA8 } /* code EBA8 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBA9 } /* code EBA9 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBAA } /* code EBAA */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBAB } /* code EBAB */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBAC } /* code EBAC */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBAD } /* code EBAD */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBAE } /* code EBAE */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBAF } /* code EBAF */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBB0 } /* code EBB0 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBB1 } /* code EBB1 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBB2 } /* code EBB2 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBB3 } /* code EBB3 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBB4 } /* code EBB4 */
  ,{  42,  42,  6, acGUI_FontHoloLensMDL2Assets27_EBB5 } /* code EBB5 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHoloLensMDL2Assets27_Prop1 = {
   0xEBA0 /* first character */
  ,0xEBB5 /* last character  */
  ,&GUI_FontHoloLensMDL2Assets27_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHoloLensMDL2Assets27 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,27 /* height of font  */
  ,27 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHoloLensMDL2Assets27_Prop1}
  ,0 /* Baseline */
  ,0 /* Height of lowercase characters */
  ,0 /* Height of capital characters */
};

